### ISSUE TITLE
Typo in README

### ISSUE THREAD

**Issue by JuanGongora** [learn-co-curriculum/js-dom-and-events-listening-to-dom-events-readme#10]
Line 25 of README typo, should be changed to:

`Copy this string of numbers, open a new tab and paste the string in to the URL`

**Comment by drakeltheryuujin** [comment]
Hi @JuanGongora 
Thank you for spotting this issue and providing feedback.
We have updated the materials and believe your issue to have been resolved.
If you do not believe that this issue has been addressed, please re-open this issue. 💙
