### ISSUE TITLE
Directions to open HTML are not for JS

### ISSUE THREAD

**Issue by aisayo** [learn-co-curriculum/js-dom-and-events-listening-to-dom-events-readme#2]
I found myself havng trouble opening the html in the browser because the directions do not speak of how to achieve this while working with JS?

**Comment by maxwellbenton** [comment]
Thank you for spotting this issue and providing feedback.

We have added instructions for opening index.html for our newer in-browser Learn environment, believe your issue to should been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
