### ISSUE TITLE
Is this a README or a lab?

### ISSUE THREAD

**Issue by FreeBreadsticks** [learn-co-curriculum/js-dom-and-events-listening-to-dom-events-readme#3]
This lab mentions opening index.html yet to students it appears as a README and they are not able to click OPEN IDE

**Comment by maxwellbenton** [comment]
Thank you for spotting this issue and providing feedback, @FreeBreadsticks.

We have updated the materials, removed the tests and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
