### ISSUE TITLE
PREVENTING THE DEFAULT BEHAVIOR

### ISSUE THREAD

**Issue by Krhorsch** [learn-co-curriculum/js-dom-and-events-listening-to-dom-events-readme#4]
In the code snippet from PREVENTING THE DEFAULT BEHAVIOR: it does not include an else statement with the console.log(e.which). So regardless of what key gets entered nothing happens

**Comment by maxwellbenton** [comment]
Thank you for spotting this issue and providing feedback, @Krhorsch.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
