### ISSUE TITLE
typo in 1st paragraph, 3rd line

### ISSUE THREAD

**Issue by missnadia** [learn-co-curriculum/js-dom-and-events-listening-to-dom-events-readme#6]
"so **gow** exactly do we interact" should be "how"

**Comment by maxwellbenton** [comment]
Thank you for spotting this issue and providing feedback, @missnadia.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
