### ISSUE TITLE
Instructions to open in browser needed earlier

### ISSUE THREAD

**Issue by arianaberger** [learn-co-curriculum/js-dom-and-events-listening-to-dom-events-readme#7]
I feel like the information below should have been introduced way earlier since we've had to fork lessons and open them in the browser for several lessons already:

Instructions for In-Browser Learn IDE Users
If you are using the Learn IDE available in your browser, you will automatically clone down the files you need when you click 'Open IDE', but in order to view index.html, you will need to use httpserver to serve the HTML page temporarily. In the terminal, type httpserver and press enter. You will see that Your server is running at ... followed by a string of numbers and dots. This string is a temporary IP address that is hosting your index.html file. Copy this string of numbers, open a new tab and past the string in to the URL bar.

Instructions for Students Using an Stand Alone Text-Editor
If you are using an standalone text editor such as Sublime or Atom, before we get started, follow these instructions to manually fork and clone the lesson repository on GitHub. In your forked and cloned copy, you'll find the index.html file, which you can then manually open up in the browser. (For instructions on opening HTML files in the browser from the Learn IDE,\ see this Help Center article.)

**Comment by sgharms** [comment]
Thanks for your feedback, we'll adjust this for the next release.
