### ISSUE TITLE
Index page issue

### ISSUE THREAD

**Issue by SMartinSci** [learn-co-curriculum/js-dom-and-events-listening-to-dom-events-readme#8]
Index.html does not work in current Linux Ubuntu Virtual Box VSC Code/Firefox setup.

**Comment by sgharms** [comment]
Hi @SMartinSci 

This issue would be perfect for the [Ask a Question](http://help.learn.co/ask-a-question/where-can-i-ask-a-question-about-a-lesson) (AAQ) feature, where the [Technical Coaches](http://help.learn.co/instructional-support/receiving-course-support/who-are-the-technical-coaches) (on [supported tracks](http://help.learn.co/instructional-support/receiving-course-support/does-my-program-or-course-have-technical-coach-support)) and fellow community members can help you figure it out. For some tips on how to take full advantage of AAQ, check out [this helpful article](http://help.learn.co/ask-a-question/how-to-optimize-time-in-ask-a-question) in the [Learn Help Center](http://help.learn.co/).

Thanks! 💙
