### ISSUE TITLE
An should be a

### ISSUE THREAD

**Issue by ValerieHMoore** [learn-co-curriculum/js-dom-and-events-listening-to-dom-events-readme#9]
"An" should be "a" in this header:
"Instructions for Students Using an Stand Alone Text-Editor"

Thank you.

**Comment by ValerieHMoore** [comment]
The same error occurs in the sentence immediately below that header.
"If you are using an standalone text editor...."

Thank you.

**Comment by drakeltheryuujin** [comment]
We have updated the materials, thanks!
